version: "3.8"

services:
  web:
    image: web:latest
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=flaskdb

    networks: 
       - flask_app_net
       
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - flask_app_net

volumes:
  db_data:

networks: 
  flask_app_net:


